# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: dschep/install-pipenv-action@v1
    - run: pipenv install -d
    - name: PyCodeStyle
      uses: ricardochaves/python-lint@v1.1.0
      with:
        python root-list: "."
        use-pylint: true
        use-pycodestyle: true

